"""
alexander_thurston.py

Compute the obvious fibered face of the Thurston norm unit ball from the
Alexander polynomial, which for braid closures is the characteristic
polynomial of the reduced Burau representation.

For alternating braids in B_3 and B_4 (using all generators), Alexander
norm = Thurston norm (proved by the author), so the Newton polytope of
the Alexander polynomial directly determines the fibered face.

The braid closure of an n-braid beta has:
  - Alexander polynomial Delta(t) = charpoly of reduced Burau at q -> t
    (up to units t^k)
  - The mapping torus has H_1 = Z (generated by t), so the Thurston norm
    ball lives in H^1(M; R) = R, and the "fibered face" is an interval
    [-c, c] where c = (1/2) * deg(Delta).

For the LINK complement (braid closure as a link in S^3), H_1 has rank
equal to the number of link components, and the Thurston norm ball lives
in H^1 = R^(components). The fibered face is a top-dimensional face of
the norm ball dual to the Newton polytope of the multivariable Alexander
polynomial.

This module handles the knot/1-component case (most alternating braids
give knots) where everything reduces to a 1D computation.
"""

from sympy import symbols, eye, zeros, Matrix, cancel, Poly, Rational, fraction, degree

q, x = symbols('q x')
t = symbols('t')


# ---- Reduced Long-Moody / Burau (imported from parent or inlined) ----

def build_Ni(i, gi, n, d):
    nb = n - 1; Id = eye(d); Zd = zeros(d)
    blocks = [[Id.copy() if r == c else Zd.copy() for c in range(nb)] for r in range(nb)]
    if i == 0:
        blocks[0][0] = -gi; blocks[0][1] = Zd
        blocks[1][0] = Id;  blocks[1][1] = Id
    elif i == n - 2:
        blocks[nb-2][nb-2] = Id;  blocks[nb-2][nb-1] = gi
        blocks[nb-1][nb-2] = Zd;  blocks[nb-1][nb-1] = -gi
    else:
        p = i - 1
        blocks[p][p] = Id;    blocks[p][p+1] = gi;    blocks[p][p+2] = Zd
        blocks[p+1][p] = Zd;  blocks[p+1][p+1] = -gi; blocks[p+1][p+2] = Zd
        blocks[p+2][p] = Zd;  blocks[p+2][p+1] = Id;  blocks[p+2][p+2] = Id
    return blocks

def left_multiply_blocks(blocks, M, nb):
    return [[M * blocks[r][c] for c in range(nb)] for r in range(nb)]

def assemble(blocks, nb, d):
    N = nb * d; M = zeros(N)
    for r in range(nb):
        for c in range(nb):
            M[r*d:(r+1)*d, c*d:(c+1)*d] = blocks[r][c]
    return M

def reduced_lm_colored(rho_g, rho_sigma, partition=None):
    n = len(rho_g); num_sigmas = len(rho_sigma); d = rho_g[0].shape[0]
    if partition is None:
        partition = [1] * n
    is_boundary = [partition[i] != partition[i+1] for i in range(num_sigmas)]
    nb = n - 1; rho_plus = []
    for i in range(num_sigmas):
        if not is_boundary[i]:
            blocks = build_Ni(i, rho_g[i], n, d)
            blocks = left_multiply_blocks(blocks, rho_sigma[i], nb)
            rho_plus.append(cancel(assemble(blocks, nb, d)))
        else:
            gi_conj = cancel(rho_g[i] * rho_g[i+1] * rho_g[i].inv())
            blocks_N  = build_Ni(i, rho_g[i], n, d)
            blocks_Np = build_Ni(i, gi_conj,  n, d)
            from sympy import zeros as _z
            def _mul(A, B, nb, d):
                C = [[_z(d) for _ in range(nb)] for _ in range(nb)]
                for r in range(nb):
                    for c in range(nb):
                        acc = _z(d)
                        for k in range(nb): acc = acc + A[r][k] * B[k][c]
                        C[r][c] = acc
                return C
            blocks_prod = _mul(blocks_Np, blocks_N, nb, d)
            si_sq = rho_sigma[i] * rho_sigma[i]
            blocks_prod = left_multiply_blocks(blocks_prod, si_sq, nb)
            rho_plus.append(cancel(assemble(blocks_prod, nb, d)))
    return rho_plus


def build_burau(n):
    """Reduced Burau generators for B_n. Returns list of (n-1)x(n-1) matrices."""
    return reduced_lm_colored([Matrix([[q]])] * n, [Matrix([[1]])] * (n - 1))


def eval_word(word, gens, inv_gens):
    M = eye(gens[0].shape[0])
    for w in word:
        if w > 0: M = M * gens[w - 1]
        else: M = M * inv_gens[-w - 1]
    return cancel(M)


# ---- Alexander polynomial ----

def alexander_poly_from_burau(word, n):
    """Compute the Alexander polynomial of the closure of an n-braid.

    The Alexander polynomial of the braid closure is (up to a unit t^k):
        Delta(t) = det(I - Burau(beta))  evaluated at q -> t

    More precisely, the (reduced) Alexander polynomial satisfies:
        Delta(t) ~ det(t*I - Burau(beta))  (charpoly evaluated at q -> t as eigenvalue parameter)

    But the standard convention is:
        Delta(t) = det(I - Burau(beta))  with Burau entries in Z[t, t^{-1}]

    We return the characteristic polynomial det(x - M) with q as the variable,
    then the Newton polytope in (x, q) gives the Alexander norm ball.

    For the 1-variable Alexander polynomial, set x = 1:
        Delta(q) = det(I - M(q))
    """
    bg = build_burau(n)
    bgi = [cancel(g.inv()) for g in bg]
    M = eval_word(word, bg, bgi)
    return M


def alexander_polynomial_1var(word, n):
    """1-variable Alexander polynomial: det(I - Burau(beta)).

    Returns a Laurent polynomial in q (up to unit q^k).
    Normalized so that Delta(1) != 0 and coefficients are symmetric.
    """
    M = alexander_poly_from_burau(word, n)
    dim = M.shape[0]
    det_expr = cancel((eye(dim) - M).det())
    return det_expr


def newton_polytope_1d(poly_expr, var=q):
    """Newton polytope of a Laurent polynomial in one variable.

    Returns (min_degree, max_degree) — the endpoints of the 1D Newton polytope.
    """
    num, den = fraction(cancel(poly_expr))
    p_num = Poly(num, var)
    q_shift = Poly(den, var).degree() if den.has(var) else 0
    degs = [d[0] - q_shift for d in p_num.monoms()]
    return (min(degs), max(degs))


def alexander_norm_1d(poly_expr, var=q):
    """Alexander norm in the 1-variable case.

    For a knot, the Alexander norm of the generator of H^1 is
    the breadth (max_deg - min_deg) of the Alexander polynomial.
    This equals the Thurston norm of the fiber class when
    Alexander norm = Thurston norm.
    """
    lo, hi = newton_polytope_1d(poly_expr, var)
    return hi - lo


def newton_polytope_2d(M):
    """Newton polytope of charpoly of M in (x, q) coordinates.

    Returns set of (x_deg, q_deg) monomials.
    """
    cp_expr = cancel(M.charpoly(x).as_expr())
    num, den = fraction(cp_expr)
    p = Poly(num, x, q)
    monoms_num = p.monoms()
    q_shift = Poly(den, q).degree() if den.has(q) else 0
    return set((xd, qd - q_shift) for (xd, qd) in monoms_num)


def convex_hull_2d(points):
    points = sorted(set(points))
    if len(points) <= 2: return points
    def cross(O, A, B):
        return (A[0]-O[0])*(B[1]-O[1]) - (A[1]-O[1])*(B[0]-O[0])
    lower = []
    for p in points:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0: lower.pop()
        lower.append(p)
    upper = []
    for p in reversed(points):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0: upper.pop()
        upper.append(p)
    return sorted(set(lower[:-1] + upper[:-1]))


# ---- Fibered face computation ----

def fibered_face_from_alexander(word, n):
    """Compute the obvious fibered face from the Alexander polynomial.

    For an n-braid beta whose closure is a fibered knot/link:

    1-variable case (knot):
        The Thurston norm ball in H^1(M; R) = R is the interval
        [-1, 1] * (1 / thurston_norm). The fibered face is the
        two endpoints {-1, 1} (top-dimensional faces of a 1D polytope).
        The Thurston norm of the fiber = Alexander norm = breadth of Delta(t).

    2-variable case (charpoly NP):
        The Newton polytope of det(xI - Burau(beta)) in (x, q) gives
        the dual of the fibered face. The fibered face vertices are
        the outer normals of the Newton polytope edges.

    Returns a dict with all computed data.
    """
    # Burau matrix
    bg = build_burau(n)
    bgi = [cancel(g.inv()) for g in bg]
    M = eval_word(word, bg, bgi)

    # 1-variable Alexander polynomial
    dim = M.shape[0]
    delta = cancel((eye(dim) - M).det())
    np_1d = newton_polytope_1d(delta)
    alex_norm = np_1d[1] - np_1d[0]

    # 2-variable Newton polytope of charpoly
    np_2d = newton_polytope_2d(M)
    hull_2d = convex_hull_2d(list(np_2d))

    # Writhe and Seifert genus
    writhe = sum(1 if w > 0 else -1 for w in word)
    # For a fibered knot from an n-braid, genus = (alexander_norm) / 2
    # (when alexander norm = thurston norm)
    genus = Rational(alex_norm, 2)

    # The fibered face in H^1 = R (knot case) is determined by:
    # Thurston norm of fiber class = alexander_norm
    # The unit ball is [-1/alex_norm, 1/alex_norm] (if alex_norm > 0)
    # The fibered face consists of the two endpoints.

    return {
        'braid_word': word,
        'n_strands': n,
        'writhe': writhe,
        'burau_matrix': M,
        'alexander_poly': delta,
        'alexander_poly_newton_1d': np_1d,
        'alexander_norm': alex_norm,
        'genus': genus,
        'charpoly_newton_2d': hull_2d,
        'thurston_norm_of_fiber': alex_norm,  # when alex norm = thurston norm
    }


def print_fibered_face(data):
    """Pretty-print the fibered face computation."""
    print(f"Braid: {data['braid_word']} in B_{data['n_strands']}")
    print(f"Writhe: {data['writhe']}")
    print(f"Alexander polynomial: {data['alexander_poly']}")
    print(f"  Newton polytope (1D): [{data['alexander_poly_newton_1d'][0]}, "
          f"{data['alexander_poly_newton_1d'][1]}]")
    print(f"  Alexander norm: {data['alexander_norm']}")
    print(f"  Genus (= alex_norm/2): {data['genus']}")
    print(f"Charpoly Newton polytope (x, q): {data['charpoly_newton_2d']}")
    print(f"Thurston norm of fiber (= Alex norm for alternating braids): "
          f"{data['thurston_norm_of_fiber']}")
    tn = data['thurston_norm_of_fiber']
    if tn > 0:
        print(f"Thurston norm unit ball (1D): [-{Rational(1, tn)}, {Rational(1, tn)}]")
        print(f"Fibered face: the two vertices {{-{Rational(1, tn)}, {Rational(1, tn)}}}")
